### ISSUE TITLE
[Bug] Butterfly registrator crashes when loading second image to register

### ISSUE THREAD

**Issue by MaryaAlbrecht** [olive-groves/butterfly_registrator#17]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I've installed the latest version of butterfly registrator on my pc (Windows 11). The installation works fine. After opening registrator it let's me load a reference image (the first image) but when loading the second image (the image to be registered) the program crashes. This happens for all images I've tried so far. Is this a known issue? I've worked with registrator before (on different PC's) and it worked really well. 

### Expected behavior

I expected to load two images to register without a problem, as I have done in the past.

**Comment by larsmaxfield** [comment]
@MaryaAlbrecht it's not a known issue — thanks for reporting.

Does it crash both when loading via drag-and-drop as well as via the open dialog ('Select' button)?

And can you confirm whether the same images which crash that installation don't crash the other installations?

I don't (yet) have a Windows 11 machine to test whether it's a Windows 11 issue. In the meantime I'll try reinstalling on Windows 10.

**Comment by larsmaxfield** [comment]
@MaryaAlbrecht in addition to the above items, can you confirm if it also crashes when adding images in the Alphascale tab? [Here's an example grayscale map you can try.](https://github.com/olive-groves/butterfly_images/blob/main/Butterfly_Images%2Fs0039V1962_Br_MAXRF.png)

I checked the latest installer for Registrator and it works on two different Windows 10 machines.

I plan to make a debugging executable for you to test soon so we can solve this.

**Comment by MaryaAlbrecht** [comment]
Hi Lars,

Thanks for your quick reply. It crashes both when opening the images by dragging and via the open dialog. I've tested the same images on a different installation (other laptop, windows 10) and there it works fine without crashing. The grayscale map you provided also opens without crashing on my laptop (windows 11)

**Comment by larsmaxfield** [comment]
Hi Marya, thanks for confirming.

If possible, can you try running this [debug executable (316 MB ZIP)](https://github.com/olive-groves/butterfly_registrator/releases/download/v1.0/debug_butterfly_registrator_v1.0-onefile-console_win64.exe.zip) in the command prompt on your Windows 11 laptop and letting me know if an error message appears in the command prompt? 

Here are steps to get that running:

**1. Copy the path to the unzipped executable**
- Download the debug executable ZIP
- Unzip (extract) the executable 
- Right-click the unzipped executable `debug_butterfly_registrator_v1.0-onefile-console_win64.exe`
- Select 'Copy as path'
![image](https://github.com/olive-groves/butterfly_registrator/assets/83759569/f00cc495-3706-4715-95f6-8f1bd6f1ef86)

**2. Run the executable via the command prompt**
- Open the command prompt:
  - Press the Windows key ⊞
  - Type `cmd`
  - Press the Enter key
![image](https://github.com/olive-groves/butterfly_registrator/assets/83759569/46e1bcc4-7d67-4126-aed9-c7d5ac23f5d9)
- Paste the path you copied into the command prompt with `Ctrl-V`
- Press the Enter key to run
![image](https://github.com/olive-groves/butterfly_registrator/assets/83759569/b899f662-bf44-42f5-8f78-9f82d469920c)

**3. Wait for the Registrator to open**
_This can take up to 60 seconds because the executable has everything packaged into one file and needs to temporarily unpack everything before it actually runs._

**4. Try to crash the Registrator by adding images**

**5. If/when it crashes, make a screenshot of the error(s) in the command prompt**

![image](https://github.com/olive-groves/butterfly_registrator/assets/83759569/b7bbe882-4c66-4980-8d07-d5c6d3bf65aa)

**Comment by MaryaAlbrecht** [comment]
Hi Lars, 
I downloaded the executable and it crashed when loading the images. 
This is wat the command prompt said:  

<img width="872" alt="Schermafbeelding 2024-06-10 211626_butterfly bug" src="https://github.com/olive-groves/butterfly_registrator/assets/170710622/eee5eb72-0c64-46dc-b041-819a544ebbac">

**Comment by larsmaxfield** [comment]
Thanks for checking.

Can you try copying the image to a different folder and then adding the image into the Registrator from there? For example, copy it outside the `Foto's Ren |® 2024` folder to `C:/Users/Marya/Documents/`, or simply copy it to your desktop.

I think the issue is caused by the special character(s) `|®` in the folder name `Foto's Ren |® 2024` where your image is stored:

![image](https://github.com/olive-groves/butterfly_registrator/assets/83759569/b0488e16-b8a6-4037-8f49-8da726adaa6e)

It seems the image processing library in Registrator can't directly handle files whose fullpaths (directories) contain special characters.*

<sup>*References:
[https://stackoverflow.com/questions/72022176/warning-cant-open-read-file-check-file-path-integrity](https://stackoverflow.com/a/74877899/20921535)
[https://stackoverflow.com/questions/44330084/opencv-imwrite-doesnt-work-because-of-special-character-in-file-path](https://stackoverflow.com/questions/44330084/opencv-imwrite-doesnt-work-because-of-special-character-in-file-path)
</sup>

**Comment by MaryaAlbrecht** [comment]
It worked! I copied the files to the desktop and everything went smoothly, then changed all the folder names and it also works smoothly. Thanks so much for your help!

**Comment by larsmaxfield** [comment]
Great to hear! Happy to help.
